#  Create instance Security Groups rules
  - name: Create instance SSH rule for remote access
    local_action:
      module: cs_securitygroup_rule
      security_group: "{{ instance_security_group_name}}"
      start_port: 22
      end_port: 22
      cidr: "{{ instance_ssh_cidr }}"
    tags: sgr
