# Secure ssh with fail to ban and optionally with two factor

  # Install fail2ban, to ban brute logins attempts
  - name: Install fail2ban
    apt:
      name: fail2ban
      cache_valid_time: 3600
    tags: ssh

  # Install google two factor authentication
  - name: Install the google authenticator
    apt:
      name: libpam-google-authenticator
      cache_valid_time: 3600
    when: "{{ ssh_enable_two_factor_auth }}"
    tags: ssh

  # Enable the google authentificator PAM module
  - name: Enable the google authenticator PAM module
    lineinfile:
      dest: /etc/pam.d/sshd
      regexp: "^auth required pam_google_authenticator.so"
      line: "auth required pam_google_authenticator.so"
      state: present
      insertafter: EOF
      create: True
    when: "{{ ssh_enable_two_factor_auth }}"
    tags: ssh

  # Deploy the SSH deamon configuration
  - name: Deploy the SSH deamon configuration
    template:
      src: sshd-config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0600'
      validate: /usr/sbin/sshd -t -f %s
      backup: yes
    tags: ssh
