# Install useful tools on the bastion

  - name: Install usefull base tools
    apt:
      name: "{{ item }}"
      cache_valid_time: 3600
    tags: tk
    with_items:
      - sysstat
      - nmap
      - iptraf
      - screen
      - git
